[platformio]
default_envs = sticks3
core_dir = .platformio

[env]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.arduino.partitions = default_8MB.csv
lib_deps =
  bblanchon/ArduinoJson@^7.3.1
  https://github.com/h2zero/NimBLE-Arduino.git#1.4.3
build_flags =
  -DESP32S3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=0

[env:sticks3]
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
lib_deps =
  ${env.lib_deps}
  M5Unified=https://github.com/m5stack/M5Unified
  M5PM1=https://github.com/m5stack/M5PM1

[env:cardputer_adv]
upload_speed = 1500000
build_flags =
  ${env.build_flags}
  -DCODEX_COMPANION_CARDPUTER=1
lib_deps =
  ${env.lib_deps}
  M5Cardputer=https://github.com/m5stack/M5Cardputer
  z3t0/IRremote@^4.7.1
